# Copyright 2019 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ingresses.networking.internal.knative.dev
  labels:
    serving.knative.dev/release: devel
    knative.dev/crd-install: "true"
spec:
  group: networking.internal.knative.dev
  versions:
  - name: v1alpha1
    served: true
    storage: true
  names:
    kind: Ingress
    plural: ingresses
    singular: ingress
    categories:
    - knative-internal
    - networking
    shortNames:
    - kingress
    - king
  scope: Namespaced
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: Ready
    type: string
    JSONPath: ".status.conditions[?(@.type=='Ready')].status"
  - name: Reason
    type: string
    JSONPath: ".status.conditions[?(@.type=='Ready')].reason"
  "validation":
    "openAPIV3Schema":
      type: object
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
          properties:
            generation:
              type: integer
              format: int64
            rules:
              type: array
              items:
                type: object
                properties:
                  hosts:
                    type: array
                    items:
                      type: string
                  http:
                    type: object
                    required:
                    - paths
                    properties:
                      paths:
                        type: array
                        items:
                          type: object
                          required:
                          - splits
                          properties:
                            appendHeaders:
                              type: object
                              additionalProperties:
                                type: string
                            path:
                              type: string
                            retries:
                              type: object
                              required:
                              - attempts
                              - perTryTimeout
                              properties:
                                attempts:
                                  type: integer
                                perTryTimeout:
                                  type: string
                            splits:
                              type: array
                              items:
                                type: object
                                required:
                                - serviceName
                                - serviceNamespace
                                - servicePort
                                properties:
                                  appendHeaders:
                                    type: object
                                    additionalProperties:
                                      type: string
                                  percent:
                                    type: integer
                                  serviceName:
                                    type: string
                                  serviceNamespace:
                                    type: string
                                  servicePort:
                                    anyOf:
                                    - type: integer
                                    - type: string
                                    x-kubernetes-int-or-string: true
                            timeout:
                              type: string
                  visibility:
                    type: string
            tls:
              type: array
              items:
                type: object
                properties:
                  hosts:
                    type: array
                    items:
                      type: string
                  privateKey:
                    type: string
                  secretName:
                    type: string
                  secretNamespace:
                    type: string
                  serverCertificate:
                    type: string
            visibility:
              type: string
        status:
          type: object
          properties:
            conditions:
              type: array
              items:
                type: object
                required:
                - status
                - type
                properties:
                  lastTransitionTime:
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  severity:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
            loadBalancer:
              type: object
              properties:
                ingress:
                  type: array
                  items:
                    type: object
                    properties:
                      domain:
                        type: string
                      domainInternal:
                        type: string
                      ip:
                        type: string
                      meshOnly:
                        type: boolean
            observedGeneration:
              type: integer
              format: int64
            privateLoadBalancer:
              type: object
              properties:
                ingress:
                  type: array
                  items:
                    type: object
                    properties:
                      domain:
                        type: string
                      domainInternal:
                        type: string
                      ip:
                        type: string
                      meshOnly:
                        type: boolean
            publicLoadBalancer:
              type: object
              properties:
                ingress:
                  type: array
                  items:
                    type: object
                    properties:
                      domain:
                        type: string
                      domainInternal:
                        type: string
                      ip:
                        type: string
                      meshOnly:
                        type: boolean
